### ISSUE TITLE
output bam file smaller than original bam file

### ISSUE THREAD

**Issue by sropri** [sandberg-lab/dataprivacy#3]
Hi Guys,

I run BAMboozle on my original bam file which is 2.9 GiB but my output file is 7.5 MiB. Shouldn't the output file be the same size? Is something wrong with my reference genome. I using the GRCh37 Human build fasta sequences, which is also 3.1 GiB. I am confused on this and your help will be appreciated

**Comment by cziegenhain** [comment]
Hi!

Yes the output indeed seems very small.
My first guess is that the chromosome names do not match between the provided fasta and the reference names present in the bam file, in which case the aligned reads that cannot be bamboozled will be discarded.

Best,
Christoph

**Comment by sropri** [comment]
Hi,

Thank you for your response and you are correct. I was able to get the correct reference genome file fasta that I aligned the fastq files with and it worked perfectly. I appreciate you taking the time to help me in this.

Ali
________________________________

**Comment by cziegenhain** [comment]
Perfect, glad it works now!
